### PR TITLE
Use different strategy for Android Chrome

### PR DESCRIPTION
**Pull request by intelliot**
With third party keyboards on Android (such as the Samsung keyboard), the `keypress` event never occurs, which breaks everything.

I noticed that the `IosStrategy` doesn't use this event. Using this strategy appears to work on Android.

We'll want to do more testing and rename the strategy, but this PR shows the minimal change that seems to work.

Keyboards:
- [ ] Google keyboard
- [ ] Samsung keyboard
- [ ] TouchPal
- [ ] Sony Xperia (pressing delete does not activate auto formatting)
- [ ] Swype

Other actions:
- [ ] Autofill
- [ ] Pastes

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I remember trying this, and there was a reason I didn't do it, but I don't remember what the reason was now.

**Comment by crookedneighbor** [comment]
Does the iOS strategy have the same paste workarounds that the Android Chrome strategy had?

**Comment by EvanHahn** [comment]
I'd make sure to check this with several different keyboards on iOS. I'd also make sure to test autofill (if you can) and pastes.

If that all works, I'd rename the strategy to something like `MobileStrategy` or something.

**Comment by intelliot** [comment]
@EvanHahn I'm guessing that where you wrote iOS, you mean Android

**Comment by EvanHahn** [comment]
@intelliot Yes, good catch.

**Comment by intelliot** [comment]
Added a couple checklists to the original PR description

**Comment by intelliot** [comment]
This doesn't always work with paste on Android. Going to try something different.

**Pull request closed without merging**
